name: Docker Web CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t docker-web .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Image
        run: docker tag docker-web ${{ secrets.DOCKER_USERNAME }}/docker-web:latest

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-web:latest
